### ISSUE TITLE
Action leaves .scannerwork owned by root 

### ISSUE THREAD

**Issue by asangas** [SonarSource/sonarqube-scan-action#22]
**Issue**
When running on a self-hosted runner, we observed that any subsequent jobs or workflows will fail when the runner attempts to clean up the workspace.  

```
Cleaning the repository
  /bin/git clean -ffdx
  warning: failed to remove .scannerwork/.sonar_lock: Permission denied
  warning: failed to remove .scannerwork/scanner-report/analysis.log: Permission denied
  warning: failed to remove .scannerwork/scanner-report/measures-15.pb: Permission denied
  warning: failed to remove .scannerwork/scanner-report/issues-15.pb: Permission denied
...
```
As described in [actions/runner#434](https://github.com/actions/runner/issues/434), files created by Docker containers are owned by root, while the runner itself does not run as root resulting in this issue.

**Possible fix**
Can the action cleanup the working directory before it exists? I'm not familiar enough with Sonar to understand whether the working directory is useful to be retained.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @asangas ,

thanks for the report. i have created https://jira.sonarsource.com/browse/SONAR-16067 to track this

**Comment by tobias-trabelsi-sonarsource** [comment]
fixed with #25

**Comment by truztee** [comment]
Hi, it still happens... I use self-hosted runner

`Error: Command failed: rm -rf "/home/github-runner/actions-runner/_work/api-core/api-core/.scannerwork"`

and here's how the folders
`github-runner@jenkins-agent:~/actions-runner/_work/api-core/api-core/.scannerwork$ ls -la`
`-rw-r--r-- 1 root          root             0 Sep 28 06:58 .sonar_lock`

**Comment by felipemullen** [comment]
Feb. 2023 Update: Issue was closed but #40 fix is not yet merged

**Comment by Mason-Lin** [comment]
Dirty, but works for me 😢
```yml
        steps:
            - name: Clean up .scannerwork folder
              run: docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli rm -rf .scannerwork
```

**Comment by jcolbert222** [comment]
> Dirty, but works for me 😢
> 
> ```yaml
>         steps:
>             - name: Clean up .scannerwork folder
>               run: docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli rm -rf .scannerwork
> ```

Heads up, this workaround is still required if you're using the sonarqube action in a job that has multiple checkout steps, as the fix that was merged in only seems to clean up the root owned dir AFTER all other job steps have been completed.

**Comment by rtrindvg** [comment]
> > Dirty, but works for me 😢
> > ```yaml
> >         steps:
> >             - name: Clean up .scannerwork folder
> >               run: docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli rm -rf .scannerwork
> > ```
> 
> Heads up, this workaround is still required if you're using the sonarqube action in a job that has multiple checkout steps, as the fix that was merged in only seems to clean up the root owned dir AFTER all other job steps have been completed.

Yep, confirmed here as well on the latest version, problem is still ongoing.

**Comment by rordi** [comment]
I used to add `--user $(id -u):$(id -g)` user and group mapping when Docker running the sonar-scanner-cli so that the Docker container does execture under same user and group as the runner on the host system. However on the `latest` tag (v10) this strategy seems to cause other issues. I simply lock the  sconar-scanner-cli to 5.0.1 for now.

```
      docker run \
        --rm \
        --user $(id -u):$(id -g) \
        --mount src="${CI_PROJECT_DIR}",target="/usr/src",type=bind \
        --env SONAR_HOST_URL="$SONAR_HOST_URL" \
        --env SONAR_LOGIN="$SONAR_TOKEN" \
        sonarsource/sonar-scanner-cli:5.0.1
```
